"In which Broadway musical does Jack sing 'There are giants in the sky'" = [ 
    "Into the Woods", "Cats", "Les Miserables", "Titanic: The Musical"
    ]

"Which Broadway musical featured a helicopter onstage?" = [
    "Miss Saigon", "South Pacific ", "Oh! What a Lovely War",
    "This is the Army"
    ]

 "What is the longest running musical in Broadway history?" = [
    "Phantom of the Opera", "Les Miserables", "Pippin",
    "the King and I"
    ]

"What is the name of Annie's dog in the musical Annie?" = [
    "Sandy", "Shandy", "Rover",
    "Champion"
    ]

 "What was the first broadway production from Disney?" = [
    "Beauty and the Beast", "Lion King", "Mary Poppins",
    "Aida"
    ]

 "Which rock opera did 'the Who' compose?" = [
    "Tommy", "Rock of Ages", "Starlight Express",
    "Rent"
    ]

"Who played Jonathan Larson in the musical film 'Tick, Tick... Boom!'?" = [
    "Andrew Garfield", "Hugh Jackman", "Zac Efron", "James Cordon"
]

"Which musical tells the story of two friends names Elphaba and Galinda?" = [
    "Wicked", "Frozen", "Chicago", "Rent"
    ]

"Where are the Sharks from in West Side Story?" = [
    "Puerto Rico", "Argentina", "Cuba", "Mexico"
    ]

"Who voiced Queen Elsa in the musical film 'Frozen'?" = [
    "Idina Menzel", "Kristen Bell", "kristin Chenoweth", "Lea Michele"
    ]


"Which musical features a group of drama students at New Yorks, High School for the Performing Arts?" = [
    "Fame", "High School Musical", "Spring Awakening", "Rent"
    ]

"Who originally played the part of Moritz in the US production, of Spring Awakening?" = [
    "John Gallagher, Jr.", "Iwan Rheon", "Jonathan Groff", "John Barrowman"
    ]

"Which musical features songs such as; Seasons of Love, I'll Cover You and One Song Glory?" = [
        "Rent", "Spring Awakening", "Bat out of Hell", "Moulin Rouge"
    ]

"Which musical did Bono and the Edge compose?" = [
        "Spider-Man: Turn off the dark", "American Idiot", "Bat out of Hell", "Rock of Ages"
    ]

"Who famously sung the song with the lines 'Sweet Transvestite'?" = [
    "Tim Curry", "George Clooney", "Hugh Jackman", "Lily Savage"
] 

"Who did the music for Jesus Christ Superstar?" = [
    "Andrew Lloyd Webber", "Time Rice", "Ben Elton", "Stephen Sondheim"
]

"Who composed Les Miserable?" = [
    "Claude-Michel Schönberg", "Alain Boublil", "Cameron Mackintosh", "Jean-Marc Natel"
    ]

"'Toot Sweets' is a song from which musical?" = [
    "Chitty Chitty Bang Bang", "Charlie and the Chocolate Factory", "Matilda", "Oliver" 
]

"Mammia Mia is a musical based on which band?" = [
    "Abba", "Baba", "Aabb", "Baab"
]

"'Aaron Burr, Sir' is a song from which musical?" = [
    "Hamilton", "Les Miserables", "South Pacific", "Sound of Music"
]

"Anne Hathaway played which character in the 2012 musical film, Les Miserables?" = [
    "Fantine", "Cosette", "Eponine", "Madame Baptistine"
]

"Hugh Jackman made his broadway debut in what musical?" = [
    "The Boy from Oz", "Oaklahoma", "The Music Man", "The River"
]

"Who sang Troy Bolton's parts in the first High School Musical?" = [
    "Drew Seeley", "Zac Efron", "Corbin Bleu", "Lucas Grabeel"
]

"Lea Michele made her broadway debut as which character?" = [
    "Young Cosette, Les Miserables", "Wendla Bergmann, Spring Awakening", "Little Girl, Ragtime", "Gavroche, Les Miserables" 
]

"What age did Stephen Sondheim pass away?" = [
    "91", "90", "92", "93"
]

"What role did Alfie Boe take in a live concert performance of Les Miserables?" =[
    "Jean Valjean", "Inspector Javert", "Enjolras", "Marius"
]

"True of False, Andrew Lloyd Webber did the music for Cats?" = [
    "True", "False"
]

"'No one Mourns the Wicked' is a song from which musical?" = [
    "Wicked", "Wizard of Oz", "the Boy from Oz", "Oz"
]

"What colour skin does Elphaba have in Wicked?" = [
    "Green", "Blue", "pink", "Turquoise"
]

"Who composed the score for The Lion King?" = [
    "Hans Zimmer", "Elton John", "Tim Rice", "Danny Elfman"
]

"Who composed the music for 'The Nightmare Before Christmas'?" = [
    "Danny Elfman", "Steve Reich", "Hans Zimmer", "Yiruma"
]

"'Masquerade / Why so Silent?' is a song from which Musical?" = [
    "Phantom of the Opera", "Les Miserables", "Miss Saigon", "Wizard of Knows"
]

"The Book of Mormon was created by the creators of another popular animated show, which show was that?" = [
    "South Park", "Simpsons", "Family Guy", "Archer"
]

"What musical is based on the music by Queen?" = [
    "We Will Rock You", "Bat out of Hell", "Guy and Dolls", "Rocky Horror Picture Show"
]

"Who wrote the music for the stage production of Matilda?" = [
    "Tim Minchin", "Elton John", "Lin-Manuel Miranda", "Andrew Lloyd Webber"
]

"What are the names of the main characters in Grease" = [
    "Danny and Sandy", "Kenickie and Rizzo", "Sonny and Sandy", "Danny and Frenchy"
]

"What is the surname of Sandy (From Grease)?" = [
    "Olsson", "Simcox", "Murdoch", "Rizzo"
]

"The music and lyrics for Guys and Dolls were written by whom?" = [
    "Frank Loesser", "Jo Swerling", "Abe Burrows", "oseph L. Mankiewicz"
]

"Alan Cumming, Kristen Bell and Neve Campbell all performed in what Movie Musical?" = [
"Reefer Madness", "Little Shop of Horrors", "Half Baked", "Annie" 
]

"What musicals format is a parody of Sesame Street?" = [
    "Avenue Q", "Book of Mormon", "Spamalot", "Urinetown"
]

"What's the name of the main character in Hairspray?" = [
    "Tracy Turnblad", "Edna Turnblad", "Penny Turnblad", "Amber Turnblad"
]

"The line 'Hasa Diga Eebowai' is from what musical?" = [
    "Book of Mormon", "Lion King", "Hamilton", "Frozen"
]

"'Hakuna Matata' means what?" = [
    "No worries", "I left the oven on", "Someone just farted", "Pick it and flick it"
]

"Which smash hit musical tells the story of the founding fathers of the United States?" = [
    "Hamilton", "Sound of Music", "Six", "West Side Story"
]

"West Side Story is based on which Shakespeare play?" = [
    "Romeo and Juliet", "Macbeth", "Hamlet", "Comedy of Errors"
]

"Who starred as Eva Peron in the film version of the musical Evita?" = [
    "Madonna", "Nicole Kidman", "Judy Garland", "Judi Dench"
]

"Who played Christine in the original stage show of Phantom of the Opera?" = [
    "Sarah Brightman", "Judy Kuhn", "Frances Ruffelle", "Patti LuPone"
]

"What is the name of the musical based on Monty Python and the Holy Grail?" = [
    "Spamalot", "Meaning of Life", "Fame", "Mary Poppins"
]

"What is Jean Valjean's prison number in the musical Les Miserables?" = [
    "24601", "20641", "26401", "21604"
]

"Who wrote the music for Billy Elliot: The Musical?" = [
    "Elton John", "Tim Minchin", "Ben Elton", "Andrew Lloyd Webber"
]

"What is the highest-grossing musical of all time?" = [
    "Lion King", "Les Miserables", "Phantom of the Opera", "Hamilton"
]

"Which actress played Roxie Hart in the movie adaptation of Chicago?" = [
    "Renee Zellweger", "Catherine Zeta-Jones", "Queen Latifa", "Denise Faye"
]

"What year did the movie adaptation of chicago release?" = [
    "2002", "2000", "2003", "2001"
]
