"In which Broadway musical does Jack sing 'There are giants in the sky'?" = [ 
    "Into the Woods", "Cats", "Les Miserables", "Titanic: The Musical"
    ]

"Which Broadway musical featured a helicopter onstage?" = [
    "Miss Saigon", "South Pacific ", "Oh! What a Lovely War",
    "This is the Army"
    ]
 